-libraryjars /home/hoshi/program/WTK22/lib/midpapi20.jar:/home/hoshi/program/WTK22/lib/wma11.jar:/home/hoshi/program/WTK22/lib/cldcapi11.jar
-injars /home/hoshi/program/WTK22/apps/RECT/bin/RECT.jar
-outjar /tmp/RECT.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
